//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Dokumentoobor8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Документ не ут.
    /// </summary>
    // *** Start programmer edit section *** (ХрДок CustomAttributes)

    // *** End programmer edit section *** (ХрДок CustomAttributes)
    [AutoAltered()]
    [Caption("Хранение документов")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокументНеУтE", new string[] {
            "ДатаСохранения as \'Дата сохранения\'"})]
    [AssociatedDetailViewAttribute("ДокументНеУтE", "ТЧСоздДок", "ТЧСоздДокE", true, "", "Т ч созд док", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("ДокументНеУтE", "ТЧУтвержДок", "ТЧУтвержДокE", true, "", "Т ч утверж док", true, new string[] {
            ""})]
    [View("ДокументНеУтL", new string[] {
            "ДатаСохранения as \'Дата сохранения\'"})]
    public class ХрДок : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаСохранения = System.DateTime.Now;
        
        private IIS.Dokumentoobor8.DetailArrayOfТЧСоздДок fТЧСоздДок;
        
        private IIS.Dokumentoobor8.DetailArrayOfТЧУтвержДок fТЧУтвержДок;
        
        // *** Start programmer edit section *** (ХрДок CustomMembers)

        // *** End programmer edit section *** (ХрДок CustomMembers)

        
        /// <summary>
        /// ДатаСохранения.
        /// </summary>
        // *** Start programmer edit section *** (ХрДок.ДатаСохранения CustomAttributes)

        // *** End programmer edit section *** (ХрДок.ДатаСохранения CustomAttributes)
        public virtual System.DateTime ДатаСохранения
        {
            get
            {
                // *** Start programmer edit section *** (ХрДок.ДатаСохранения Get start)

                // *** End programmer edit section *** (ХрДок.ДатаСохранения Get start)
                System.DateTime result = this.fДатаСохранения;
                // *** Start programmer edit section *** (ХрДок.ДатаСохранения Get end)

                // *** End programmer edit section *** (ХрДок.ДатаСохранения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ХрДок.ДатаСохранения Set start)

                // *** End programmer edit section *** (ХрДок.ДатаСохранения Set start)
                this.fДатаСохранения = value;
                // *** Start programmer edit section *** (ХрДок.ДатаСохранения Set end)

                // *** End programmer edit section *** (ХрДок.ДатаСохранения Set end)
            }
        }
        
        /// <summary>
        /// Документ не ут.
        /// </summary>
        // *** Start programmer edit section *** (ХрДок.ТЧСоздДок CustomAttributes)

        // *** End programmer edit section *** (ХрДок.ТЧСоздДок CustomAttributes)
        public virtual IIS.Dokumentoobor8.DetailArrayOfТЧСоздДок ТЧСоздДок
        {
            get
            {
                // *** Start programmer edit section *** (ХрДок.ТЧСоздДок Get start)

                // *** End programmer edit section *** (ХрДок.ТЧСоздДок Get start)
                if ((this.fТЧСоздДок == null))
                {
                    this.fТЧСоздДок = new IIS.Dokumentoobor8.DetailArrayOfТЧСоздДок(this);
                }
                IIS.Dokumentoobor8.DetailArrayOfТЧСоздДок result = this.fТЧСоздДок;
                // *** Start programmer edit section *** (ХрДок.ТЧСоздДок Get end)

                // *** End programmer edit section *** (ХрДок.ТЧСоздДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ХрДок.ТЧСоздДок Set start)

                // *** End programmer edit section *** (ХрДок.ТЧСоздДок Set start)
                this.fТЧСоздДок = value;
                // *** Start programmer edit section *** (ХрДок.ТЧСоздДок Set end)

                // *** End programmer edit section *** (ХрДок.ТЧСоздДок Set end)
            }
        }
        
        /// <summary>
        /// Документ не ут.
        /// </summary>
        // *** Start programmer edit section *** (ХрДок.ТЧУтвержДок CustomAttributes)

        // *** End programmer edit section *** (ХрДок.ТЧУтвержДок CustomAttributes)
        public virtual IIS.Dokumentoobor8.DetailArrayOfТЧУтвержДок ТЧУтвержДок
        {
            get
            {
                // *** Start programmer edit section *** (ХрДок.ТЧУтвержДок Get start)

                // *** End programmer edit section *** (ХрДок.ТЧУтвержДок Get start)
                if ((this.fТЧУтвержДок == null))
                {
                    this.fТЧУтвержДок = new IIS.Dokumentoobor8.DetailArrayOfТЧУтвержДок(this);
                }
                IIS.Dokumentoobor8.DetailArrayOfТЧУтвержДок result = this.fТЧУтвержДок;
                // *** Start programmer edit section *** (ХрДок.ТЧУтвержДок Get end)

                // *** End programmer edit section *** (ХрДок.ТЧУтвержДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ХрДок.ТЧУтвержДок Set start)

                // *** End programmer edit section *** (ХрДок.ТЧУтвержДок Set start)
                this.fТЧУтвержДок = value;
                // *** Start programmer edit section *** (ХрДок.ТЧУтвержДок Set end)

                // *** End programmer edit section *** (ХрДок.ТЧУтвержДок Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокументНеУтE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокументНеУтE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокументНеУтE", typeof(IIS.Dokumentoobor8.ХрДок));
                }
            }
            
            /// <summary>
            /// "ДокументНеУтL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокументНеУтL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокументНеУтL", typeof(IIS.Dokumentoobor8.ХрДок));
                }
            }
        }
    }
}
